### Test
GET http://localhost:6000/ HTTP/1.1

### Register
POST http://localhost:6000/user/register HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "email": "test@gmail.com",
    "password": "test"
}

### Login
POST http://localhost:6000/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### Recommendations
GET http://localhost:5000/recommendations/66d87186bb03c1a5e68dcc17 HTTP/1.1

### Like
POST http://localhost:5000/recommendations/like HTTP/1.1
Content-Type: application/json

{
    "userId": "66d87186bb03c1a5e68dcc17",
    "productId": "b"
}

### Dislike
POST http://localhost:6000/recommendations/dislike HTTP/1.1
Content-Type: application/json

{
    "userId": "66d83a73b753aef362c5ccc9",
    "productId": "66d87186bb03c1a5e68dcc15"
}

### Products
GET http://localhost:5000/products HTTP/1.1
